/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appPackage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author singhakshay16
 */
public class p1 extends javax.swing.JFrame {

    /**
     * Creates new form p1
     */
    public p1() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("1st.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        p1t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        cb1 = new javax.swing.JRadioButton();
        cb2 = new javax.swing.JRadioButton();
        cb3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();

        p1t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Design by Aryan-The Diciple");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Enter The Value Of N:-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, 219, 34));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("INPUT X[i],Y[i]");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 196, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Result:-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 90, 44));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 110, 40));

        t1.setColumns(20);
        t1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 296, 518, 228));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, 619));

        buttonGroup1.add(cb1);
        cb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(153, 0, 153));
        cb1.setText("Trapezoidal rule");
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 190, -1, -1));

        buttonGroup1.add(cb2);
        cb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb2.setForeground(new java.awt.Color(153, 0, 153));
        cb2.setText("simpson 1/3th");
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 190, -1, -1));

        buttonGroup1.add(cb3);
        cb3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb3.setForeground(new java.awt.Color(153, 0, 153));
        cb3.setText("simpson 3/8th");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 190, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appPackage/2st.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        jLabel4.setBackground(new java.awt.Color(38, 255, 237));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("          Numerical Integration");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 590, 70));
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 330, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

int n;
n=Integer.parseInt(T1.getText());
   
if(cb1.isSelected())
{   
   t1.append("\n\nBy using Trapezoidal rule :-\n");
}
if (cb2.isSelected())
{
   t1.append("\n\nBy using Simpson 1/3th :-\n");
}
if(cb3.isSelected())
{
   t1.append("\n\nBy using Simpson 2/8th :-\n"); 
}
   int X[],Y[];
   X=new int[100];
   Y=new int[100];
    JOptionPane.showMessageDialog(null,"WELCOME TO ARRAY INPUT");
     t1.append("X[i]=");
   for(int i=0;i<=n;i++)
   {
     int q=Integer.parseInt(JOptionPane.showInputDialog("Enter X[i] number"));
      X[i]=q;
       t1.append("  "+X[i]);
   }
   t1.append("\n");
   t1.append("Y[i]=");
   for(int i=0;i<=n;i++)
   {
     int q=Integer.parseInt(JOptionPane.showInputDialog("Enter Y[i] number"));
      Y[i]=q;
      t1.append("  "+Y[i]);
   }
  float s=0,h=X[1]-X[0];
t1.append("\nResult= ");
if(cb1.isSelected())
{   
    s+=(Y[0]+Y[n])/2;
    for(int i=1;i<n;i++)
       s+=Y[i];
}
if (cb2.isSelected())
{
    s+=(Y[0]+Y[n]);
    for (int i=1;i<n;i++)
	if (i%2==0)
	s+=2*Y[i];
	else
	s+=4*Y[i];
    s*=(h)/3;
}
if(cb3.isSelected())
{
    s+=(Y[0]+Y[n]);
    for (int i=1;i<n;i++)
	if (i%3==0)
	s+=2*Y[i];
	else
	s+=3*Y[i];
    s=(s*(h)*3)/8;
}

t1.append(" "+s);













        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 EXIT object1=new EXIT();
 object1.setVisible(true);
 this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 p3 object1=new p3();
 object1.setVisible(true);
 this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cb1;
    private javax.swing.JRadioButton cb2;
    private javax.swing.JRadioButton cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField p1t1;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
